integration_tests:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: service-account-json
      project: avo-audit
      dataset: integration_tests
      threads: 1
      timeout_seconds: 300
      priority: interactive
      keyfile_json:
        type: "service_account"
        project_id: "{{ env_var('BIGQUERY_PROJECT') }}"
        private_key_id: "{{ env_var('PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('PRIVATE_KEY') }}"
        client_email: "{{ env_var('client_email') }}"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "{{ env_var('CLIENT_X509_CERT_URL') }}"
