integration_tests:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: service-account-json
      project: avo-audit
      dataset: integration_tests
      threads: 1
      timeout_seconds: 300
      priority: interactive
      keyfile_json:
          type: "{{ env_var('BIGQUERY_TYPE') }}"
          project_id: "avo-audit"
          private_key_id: "{{ env_var('BIGQUERY_PRIVATE_KEY_ID') }}"
          private_key: "{{ env_var('BIGQUERY_PRIVATE_KEY') }}"
          client_email: "{{ env_var('BIGQUERY_CLIENT_EMAIL') }}"
          client_id: "{{ env_var('BIGQUERY_CLIENT_ID') }}"
          auth_uri: "{{ env_var('BIGQUERY_AUTH_URI') }}"
          token_uri: "{{ env_var('BIGQUERY_TOKEN_URI') }}"
          auth_provider_x509_cert_url: "{{ env_var('BIGQUERY_AUTH_PROVIDER_X509_CERT_URL') }}"
          client_x509_cert_url: "{{ env_var('BIGQUERY_CLIENT_X509_CERT_URL') }}"
        
