# This is a basic workflow to help you get started with Actions

name: CI

env:
  DBT_PROFILES_DIR: ./integration_tests/
  DBT_VERSION: 0.21.0

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]


# will cancel previous workflows triggered by the same event and for the same ref for PRs or same SHA otherwise
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  integration_bigquery:
    name: integration-bigquery
    runs-on: ubuntu-latest
    container: python:3.8-buster
    env:
      BIGQUERY_PROJECT: ${{ secrets.BIGQUERY_PROJECT }}
      BIGQUERY_SERVICE_ACCOUNT_JSON: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_JSON }}
      BIGQUERY_KEYFILE: ./bigquery-service-key.json

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install dbt==${DBT_VERSION}
          dbt deps
          dbt --version
      - name: Test database connection
        run: |
          echo "${BIGQUERY_SERVICE_ACCOUNT_JSON}" > ${BIGQUERY_KEYFILE}
          dbt debug --target bigquery
      - name: Run tests
        run: |
          dbt seed --target bigquery
          dbt test --target bigquery